# Generated by Django 3.1.6 on 2021-03-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('rent', models.IntegerField()),
                ('size', models.IntegerField()),
                ('buildDate', models.DateTimeField(auto_now_add=True)),
                ('livingNumber', models.IntegerField()),
                ('nearestStation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.BooleanField(default=True, help_text='Are you happy for us to anonymously upload your review to our property review site? Your review will be anonymised')),
                ('livingConfirmation', models.BooleanField(default=True, help_text='Do you confirm that you live or lived at the property in question?')),
                ('firstName', models.CharField(max_length=255)),
                ('contactPermisssion', models.BooleanField(default=True, help_text='Do you want us to contact you when we upload your review?')),
                ('reviewDate', models.DateField(auto_now_add=True)),
                ('moveIn', models.DateField()),
                ('moveOut', models.DateField()),
                ('occupation', models.CharField(choices=[(1, 'Student'), (2, 'Non student')], default=1, max_length=255)),
                ('bedroomNumber', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=3, help_text='How many bedrooms was the house? ')),
                ('overallRating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='How would you rate the property out of 5? [conditon, responsiveness of landlord/property management company/value for money/neighbourhood]')),
                ('overallMaintainance', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='What was the condition of the property and how well was it maintained? ')),
                ('buildingQuality', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='What was the quality of the building [considering pests, rodents, cleanliness and any damp or mould]?')),
                ('furnishings', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='What was the quality of the furnishings? ')),
                ('water', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='How would you rate the water, heating and insulation of the property?')),
                ('whiteGoods', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='How would you rate the quality of the white goods (dishwasher, washing machine, electrical appliances)')),
                ('maintainanceComment', models.CharField(blank=True, help_text='Any other comment?', max_length=255, null=True)),
                ('overallLandlord', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='How would you rate the landlord/property management company?')),
                ('responsiveness', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='How responsive was the landlord/property management company to an issues that were raised? ')),
                ('repairQuality', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='How would you rate the quality of any repairs to any issues raised?')),
                ('movingInExperiance', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='How would you rate the moving in process and experience? [Moving in dates, state of property etc] ')),
                ('movingOutExperiance', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='How would you rate the moving out process and experience? [Deposit, cleanling fees, fairness] ')),
                ('landlordComment', models.CharField(blank=True, help_text='Any other comment?', max_length=255, null=True)),
                ('rent', models.PositiveIntegerField(default=500, help_text='What was your monthly rent?')),
                ('valueForMoney', models.BooleanField(default=True, help_text='Was the property worth the money?')),
                ('areaSafety', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='How safe did you feel in the area?')),
                ('areaEnjoyment', models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=3, help_text='How much did you enjoy living in the area? ')),
                ('areaEnjoymentReason', models.CharField(blank=True, help_text='why? [amenities, closeness to transport, noise]', max_length=255, null=True)),
                ('recomendation', models.BooleanField(default=True, help_text='Would you reccomend this property to others? ')),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='beta.property')),
            ],
        ),
    ]
