# Generated by Django 3.1.6 on 2021-03-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
