# Generated by Django 3.1.6 on 2021-03-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_review_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='buildDate',
        ),
        migrations.RemoveField(
            model_name='property',
            name='livingNumber',
        ),
        migrations.RemoveField(
            model_name='property',
            name='nearestStation',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='size',
        ),
        migrations.AddField(
            model_name='property',
            name='aptNumber',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('house', 'house'), ('flat', 'flat'), ('other', 'other')], default='flat', help_text='Is the property a house or flat?', max_length=255),
        ),
    ]
