# Generated by Django 3.1.6 on 2021-03-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0005_property_fulladdress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='fullAddress',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
